# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMSample3-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMSample3-RxSwift
  pod 'Alamofire', '~> 5.4'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 6.0'
end
